### PR TITLE
Update

### PR DESCRIPTION
**Pull request by c0lide**

### CODE REVIEW

**Comment by rosie-alt** [comment]
**Please delete this immediately.**

I am tired of this. I have given you enough chances. This is a deliberate attempt at completely stealing the Azalea code without any attribution to Azalea or me anywhere, NOT EVEN IN THE LICENSE.

I have had enough. Delete this repository or I **will** go through legal hell to get this taken down with a DMCA strike. I will work out no deals with you, you purposefully disabled my permission to submit PRs or Issues because you are aware that I will find this and request for it to be taken down. I know it is the latest code because I wrote it.

The code is not using MIT license, or any license. You cant use it. Take this down. You have 24 hours.

Love, Rosie.

**Comment by mugman174** [comment]
> **Please delete this immediately.**
> 
> I am tired of this cat and mouse game of constantly tracking your new repository where you steal my code. I have given you enough chances. This is a deliberate attempt at completely stealing the Azalea code without any attribution to Azalea or me anywhere, NOT EVEN IN THE LICENSE.
> 
> I have had enough. Delete this repository or I **will** go through legal hell to get this taken down with a DMCA strike. I will work out no deals with you. You purposefully disabled my permission to submit PRs or Issues because you are aware that I will find this and request it to be taken down. I know it is the latest code because I wrote it.
> 
> The Azalea code is not using MIT license, or any license. It is under copyright law. You can't use it. **Take this repository down.** You have **24 hours**. If you make any new repositories which use the Azalea code under a new name like this project or any of the prequels, I will find them and ask for them to be taken down in the same manner as this repository, until you finally stop stealing my code.
> 
> This time I will not give up, so stop thinking you can copy my code without consequences, as I do care unlike the author of magic-notes and I will do whatever it takes to get an obvious copyright infringement taken down. **This is your final warning.**

This comment has been sent on behalf of @acquitelol.

**Comment by mugman174** [comment]
Also, if you continue blocking either @acquitelol or me from this repository, legal action will be taken before the 24 hours mentioned.

**Comment by Panniku** [comment]
Please look at [this comment](https://github.com/c0lide/SparxSolver/pull/73#issuecomment-1763256724)

**Comment by Panniku** [comment]
Please look at [this comment](https://github.com/c0lide/SparxSolver/pull/73#issuecomment-1763256724)

**Comment by Panniku** [comment]
@c0lide @NajmAjmal

**Pull request merged**
